# Handles the timesnap lookup service
<IfModule !wsgi_module>
        LoadModule wsgi_module modules/mod_wsgi.so
</IfModule>

# Block to set up the time service using mod_wsgi
WSGIScriptAlias /time_service/time /var/www/html/time_service/wsgi_app_time_service.py
WSGIScriptAlias /oe2-time-service-proxy-onearth-time-service /var/www/html/time_service/wsgi_app_time_service.py

<Directory /var/www/html/time_service>
        WSGIProcessGroup time_service
        WSGIApplicationGroup %{GLOBAL}
        Require all granted
</Directory>

WSGIDaemonProcess time_service python-path=/var/www/html/time_service processes=8 threads=64