# For consistency, versions should be kept in sync with those in:
# /requirements.txt
# /docker/tools/Dockerfile
name: mrfgen
channels:
  - conda-forge
  - nodefaults
dependencies:
  - python =3.12
  #
  # For building the Cython-based C extension
  - c-compiler
  - cython =3.1.2
  - setuptools =80.9.0
  #
  # mrfgen dependencies
  - gdal =3.6.4
  - numpy =1.26.4
  - pillow =10
  - rasterio =1.3
