# For consistency, versions should be kept in sync with those in:
# /requirements.txt
# /docker/tools/Dockerfile
name: mrfgen
channels:
  - conda-forge
  - nodefaults
dependencies:
  - python =3.10
  #
  # For building the Cython-based C extension
  - c-compiler
  - cython =3.0.11
  - setuptools =70.0.0
  #
  # mrfgen dependencies
  - gdal =3.6.4
  - numpy =1.25.2
  - pillow =10
  - rasterio =1.3
