# High Concurrency Tuning
# Enable KeepAlive to allow browsers to pull multiple tiles per connection
KeepAlive On

# Max number of requests allowed per persistent connection
MaxKeepAliveRequests 100

# Drop from 15s to 2s. 
# This kicks out idle clients faster so new requests can take their place.
KeepAliveTimeout 2

# Hide version info for security/slightly smaller headers
ServerSignature Off
ServerTokens Prod
