time_service_uri: "http://onearth-time-service/time_service/time"
time_service_keys: ["epsg3413"]
gc_service_uri: "http://onearth-capabilities/wmts/epsg3413/best/gc"
exclude_layers:
  - 'Reference_Labels'
  - 'Reference_Labels_15m'
  - 'Reference_Features'
  - 'Reference_Features_15m'
tms_defs_file: "/etc/onearth/config/conf/tilematrixsets.xml"
layer_config_source: "/etc/onearth/config/layers/epsg3413/best/"
apache_config_location: "/etc/httpd/conf.d/"
base_uri_gc: "http://localhost/wmts/epsg3413/best/"
base_uri_gts: "http://localhost/twms/epsg3413/best/"
base_uri_meta: "https://gibs.earthdata.nasa.gov"
epsg_code: "EPSG:3413"
gc_service:
  internal_endpoint: "/var/www/html/wmts/epsg3413/best"
  external_endpoint: "/wmts/epsg3413/best/gc"
  config_prefix: "epsg3413_best_gc_service"
  gc_header_file: "/etc/onearth/config/conf/epsg3413_best_header_gc.xml"
  gts_header_file: "/etc/onearth/config/conf/epsg3413_best_header_gts.xml"
  twms_gc_header_file: "/etc/onearth/config/conf/epsg3413_best_header_twms_gc.xml"
wmts_service:
  internal_endpoint: "/var/www/html/wmts/epsg3413/best"
  external_endpoint: "/wmts/epsg3413/best"
  config_prefix: "epsg3413_best"
twms_service:
  internal_endpoint: "/var/www/html/twms/epsg3413/best"
  external_endpoint: "/twms/epsg3413/best"
mapserver:
  redirect_endpoint: "/var/www/html/mapserver/epsg3413/best"
  external_endpoint: "/wms/epsg3413/best"
  internal_endpoint: "/var/www/html/wms/epsg3413/best"
  config_prefix: "epsg3413_best_wms_time_service"
  mapfile_header:  "/etc/onearth/config/mapserver/epsg3413.header"
  mapfile_location: "/etc/onearth/config/mapserver/epsg3413_best.map"
  source_wmts_gc_uri: "https://gibs.earthdata.nasa.gov/wmts/epsg3413/best/1.0.0/WMTSCapabilities.xml"