time_service_uri: "http://onearth-time-service/time_service/time"
time_service_keys: ["epsg4326"]
gc_service_uri: "http://onearth-capabilities/wmts/epsg4326/all/gc"
exclude_layers: []
tms_defs_file: "/etc/onearth/config/conf/tilematrixsets.xml"
layer_config_source: "/etc/onearth/config/layers/epsg4326/all/"
apache_config_location: "/etc/httpd/conf.d/"
base_uri_gc: "http://localhost/wmts/epsg4326/all/"
base_uri_gts: "http://localhost/twms/epsg4326/all/"
base_uri_meta: "http://localhost"
epsg_code: "EPSG:4326"
gc_service:
  internal_endpoint: "/var/www/html/wmts/epsg4326/all"
  external_endpoint: "/wmts/epsg4326/all/gc"
  config_prefix: "epsg4326_all_gc_service"
  gc_header_file: "/etc/onearth/config/conf/epsg4326_header_gc.xml"
  gts_header_file: "/etc/onearth/config/conf/epsg4326_header_gts.xml"
  twms_gc_header_file: "/etc/onearth/config/conf/epsg4326_header_twms_gc.xml"
wmts_service:
  internal_endpoint: "/var/www/html/wmts/epsg4326/all"
  external_endpoint: "/wmts/epsg4326/all"
  config_prefix: "epsg4326_all"
twms_service:
  internal_endpoint: "/var/www/html/twms/epsg4326/all"
  external_endpoint: "/twms/epsg4326/all"
mapserver:
  internal_endpoint: "/var/www/html/wms/epsg4326/all"
  external_endpoint: "/wms/epsg4326/all"
  redirect_endpoint: "/var/www/html/mapserver/epsg4326/all"
  config_prefix: "epsg4326_all_wms_time_service"
  mapfile_header: "/etc/onearth/config/mapserver/epsg4326_all.header"
  mapfile_location: "/etc/onearth/config/mapserver/epsg4326_all.map"
  source_wmts_gc_uri: "http://localhost/wmts/epsg4326/all/1.0.0/WMTSCapabilities.xml"
  replace_with_local: "http://localhost"