abstract: AMSRU2_Soil_Moisture_NPD_Day_v2_STD abstract
best_layer: AMSRU2_Soil_Moisture_NPD_Day
layer_id: AMSRU2_Soil_Moisture_NPD_Day_v2_STD
layer_name: AMSRU2 Soil Moisture NPD Day v2 STD tileset
layer_title: Soil Moisture (Normalized Polarization Difference, Day, v2, AMSRU2, GCOM-W1)
metadata:
- {'xlink:href': '{base_uri_meta}/colormaps/v1.0/AMSR_Soil_Moisture.xml', 'xlink:role': 'http://earthdata.nasa.gov/gibs/metadata-type/colormap/1.0', 'xlink:title': 'GIBS Color Map: Data - RGB Mapping', 'xlink:type': 'simple'}
- {'xlink:href': '{base_uri_meta}/colormaps/v1.3/AMSR_Soil_Moisture.xml', 'xlink:role': 'http://earthdata.nasa.gov/gibs/metadata-type/colormap/1.3', 'xlink:title': 'GIBS Color Map: Data - RGB Mapping', 'xlink:type': 'simple'}
- {'xlink:href': '{base_uri_meta}/colormaps/v1.3/AMSR_Soil_Moisture.xml', 'xlink:role': 'http://earthdata.nasa.gov/gibs/metadata-type/colormap/', 'xlink:title': 'GIBS Color Map: Data - RGB Mapping', 'xlink:type': 'simple'}
mime_type: image/png
projection: EPSG:4326
source_mrf:
  bands: 1
  bbox: -180,-90,180,90
  data_file_uri: '{S3_URL}/epsg4326'
  empty_tile: /etc/onearth/empty_tiles/AMSR_Soil_Moisture.png
  idx_path: /onearth/idx/epsg4326
  size_x: 20480
  size_y: 10240
  tile_size_x: 512
  tile_size_y: 512
  year_dir: true
static: false
style:
  default: true
  identifier: default
  title: default
  urls:
  - {format: 'image/svg+xml', height: 85.5, width: 378.0, 'xlink:href': '{base_uri_meta}/legends/AMSR_Soil_Moisture_H.svg', 'xlink:role': 'http://earthdata.nasa.gov/gibs/legend-type/horizontal', 'xlink:title': 'GIBS Color Map Legend: Horizontal', 'xlink:type': 'simple'}
  - {format: 'image/svg+xml', height: 288.0, width: 135.0, 'xlink:href': '{base_uri_meta}/legends/AMSR_Soil_Moisture_V.svg', 'xlink:role': 'http://earthdata.nasa.gov/gibs/legend-type/vertical', 'xlink:title': 'GIBS Color Map Legend: Vertical', 'xlink:type': 'simple'}
tilematrixset: 2km
time_config:
- DETECT/P1D
