INCLUDES = -I /usr/include/httpd -I /usr/local/apr/include/apr-1
MOD_PATH = /usr/lib64/httpd/modules
HTTPD_INCLUDES_PATH = /usr/include/httpd
DEST = $(MOD_PATH)
LIBTOOL = /usr/lib64/apr-1/build/libtool

